/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_common_android_ads_KKAds */

#ifndef _Included_com_common_android_ads_KKAds
#define _Included_com_common_android_ads_KKAds
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_common_android_ads_KKAds
 * Method:    nativeAdLoadSuccessfully
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_KKAds_nativeAdLoadSuccessfully
  (JNIEnv *, jobject);

/*
 * Class:     com_common_android_ads_KKAds
 * Method:    nativeAdLoadFailed
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_KKAds_nativeAdLoadFailed
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_common_android_ads_KKAds
 * Method:    nativeClickedBannerAd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_KKAds_nativeClickedBannerAd
  (JNIEnv *, jobject);

/*
 * Class:     com_common_android_ads_KKAds
 * Method:    nativeInterstitialAdLoaded
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_KKAds_nativeInterstitialAdLoaded
  (JNIEnv *, jobject);

/*
 * Class:     com_common_android_ads_KKAds
 * Method:    nativeInterstitialAdFailed
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_KKAds_nativeInterstitialAdFailed
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_common_android_ads_KKAds
 * Method:    nativeInterstitialAdShown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_KKAds_nativeInterstitialAdShown
  (JNIEnv *, jobject);

/*
 * Class:     com_common_android_ads_KKAds
 * Method:    nativeInterstitialAdDismissed
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_KKAds_nativeInterstitialAdDismissed
  (JNIEnv *, jobject);

/*
 * Class:     com_common_android_ads_KKAds
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_KKAds_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_common_android_ads_KKAds
 * Method:    nativeDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_KKAds_nativeDestroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
