/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vungle_publisher_KKVungle */

#ifndef _Included_com_vungle_publisher_KKVungle
#define _Included_com_vungle_publisher_KKVungle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vungle_publisher_KKVungle
 * Method:    nativeAdCacheSuccessfully
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_vungle_publisher_KKVungle_nativeAdCacheSuccessfully
  (JNIEnv *, jobject);

/*
 * Class:     com_vungle_publisher_KKVungle
 * Method:    nativeAdLoadFailed
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_vungle_publisher_KKVungle_nativeAdLoadFailed
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_vungle_publisher_KKVungle
 * Method:    nativeAdRewarded
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_vungle_publisher_KKVungle_nativeAdRewarded
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_vungle_publisher_KKVungle
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_vungle_publisher_KKVungle_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_vungle_publisher_KKVungle
 * Method:    nativeDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_vungle_publisher_KKVungle_nativeDestroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
