/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_common_android_jni_KKShare */

#ifndef _Included_com_common_android_jni_KKShare
#define _Included_com_common_android_jni_KKShare
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_common_android_jni_KKShare
 * Method:    nativeShareSucceed
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_common_android_jni_KKShare_nativeShareSucceed
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_common_android_jni_KKShare
 * Method:    nativeShareCancel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_common_android_jni_KKShare_nativeShareCancel
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
