/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_common_android_jni_KKDialogManager */

#ifndef _Included_com_common_android_jni_KKDialogManager
#define _Included_com_common_android_jni_KKDialogManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_common_android_jni_KKDialogManager
 * Method:    DialogNegativeCLicked
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_common_android_jni_KKDialogManager_DialogNegativeCLicked
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_common_android_jni_KKDialogManager
 * Method:    DialogPositiveCLicked
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_common_android_jni_KKDialogManager_DialogPositiveCLicked
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
