/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_common_android_jni_KKSystemFunction */

#ifndef _Included_com_common_android_jni_KKSystemFunction
#define _Included_com_common_android_jni_KKSystemFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_common_android_jni_KKSystemFunction
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_jni_KKSystemFunction_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_common_android_jni_KKSystemFunction
 * Method:    nativeDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_jni_KKSystemFunction_nativeDestroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
